name: Build and Deploy
on:
  push:
    branches: [develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repository Name
        run: echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
          # This uses the Dockerfile we created above
          file: ./Dockerfile

      - name: Deploy to Coolify
        run: |
          curl -X GET "${{ secrets.COOLIFY_WEBHOOK }}"
